# Introduction {#intro}

Resources  

 * [INTRODUCTION TO MACHINE LEARNING](http://alex.smola.org/drafts/thebook.pdf)

3 types of data  

 * Structured Data (tables form)  
 * Semi-structured Data (e.g., XML, JSON, HTML)  
 * Unstructured Data  
    + Texts  
    + Images: Videos, photos,  
    + Networks: Social Networks  


This section based on notes in "Analyzing Unstructured Data" course taught by professor Kunpeng Zhang.  

 * ML is concerned with the the development, the analysis, and the application of algorithm that allow computers to learn  
 * Learning:  
    + A computer learns if it improves its performance at some tasks with experience (i.e., data)  
    + Extracting a model of system from the sole observation (or the simulation)  
    + A model = some relationships between the variables used to describe the system.  
 * Goals:  
    + Make prediction  
    + Understand the underlying mechanisms.  
 * Learning if useful when:  
    + Human expertise does not exist (navigating on Mars)  
    + Humans are unable to explain their expertise (speech recognition)  
    + Solution changes in time (routing on a computer network)  
    Solution needs to be adapted to particular cases (user biometrics)  
 * Applications in different domains:  
    + Retail: Market basket analysis, customer relationship management (CRM)  
    + Finance: Credit scoring, fraud detection.  
    + Manufacturing: Optimization, troubleshooting  
    + Medicine: medical diagnosis  
    + Telecommunications: Quality of service optimization, routing  
    + Bioinformatics: Motifs, alignment WEb mining, search engines.  
 * Steps  
    * Data generation: data types, sample size  
    * Preprocessing: normalization, missing values, feature selection/extraction  
    * Machine Learning: Hypothesis, choice of learning paradigm/algorithm.  
    * Hypothesis validation: cross-validation, model deployment.  
 * Types of machine learning:  
    + Supervised: manually label variables  
    + Unsupervised:  
 * Training and testing  
    + Training is the process of making the machine learn  
    + No free lunch:  
        - Training set and testing set come from the same distribution  
        - Need to make some assumptions.  
 * Factors affecting the performance:  
    + Types of training provided  
    + The form and extend of prior knowledge  
    + Type of feedback provided  
    + The learning algorithms used  
 * Two factors:  
    + Modeling  
    + optimization  
 * Algorithms:  
    + ML depends on algorithms.  
    + The algorithms control the search to find and build the knowledge structures  
    + The learning algorithms should extract useful information from training examples.  
 * Types of learning (algorithms):  
    + Supervised learning ($\{ X_n \in R^d, y_n \in R\}^N_{n=1}$)  
        - Prediction  
        - Classification (discrete labels), regression (real values)  
    + Unsupervised learning ($\{ X_n \in R^d\}^N_{n=1}$)  
        - Clustering  
        - Probability distribution estimation  
        - Finding association (in features)  
        - Dimension reduction  
    + Semi-supervised learning  
    + Reinforcement learning  
        - Decision making (robot, chess machine)


