# Multivariate Adaptive Regression Splines

-   Also known as MARS

-   an adaptive procedure for regression when there are a large number of input variables.

-   Can also be viewed as a generalization of stepwise linear regression or a modification of the [CART][Classification and Regression Trees] procedure that improves its performance in the regression setting

-   uses expansions in the piecewise linear [basis function][Basis Function Representations]

-   To mimic [CART][Classification and Regression Trees], the MARS procedure makes the following changes:

    -   Replace the piece wise linear basis function by step functions (e..g, $I(x-t>0); I(x-t) \le 0)$

    -   When a model term is in a multiplication by a candidate term, it gets replaced by the interaction, and hence it not available for further interaction

    -   With these changes, the MARS forward procedure is similar to the CART tree-growing algorithm (i.e., multiplying a step function by a pair of reflected step functions is equivalent to splitting a node at the step. The second restriction is a node may not be split more than once (leaning to the binary tree structure)). Hence, MARS is more powerful because it allows for additive structures because it's not limited to the binary tree structure

-   MARS is not used that much today anymore.

Consider basis function of the form ("+" means "positive part" with a not at t)

$$
(x-t)_+
\begin{cases}
x-t & \text{ if } x > t \\
0 & \text{otherwise}
\end{cases}
$$

and

$$
(t-x)_+
\begin{cases}
t- x & \text{ if } x < t \\
0 & \text{otherwise}
\end{cases}
$$

These are linear splines and the pair is **reflected pair**.

We form such reflected pairs for each input $X_j$ with knots at each observed value $x_{ij}$ of that input variable.

The collection of basis function is

$$
C = \{(X_j - t)_+ , (t-X_j)_+\}_{t \in \{x_{1j}, \dots, x_{nj} \}}, j = 1, \dots, p
$$

there can be as many as $2np$ basis functions (if all of the input values are distinct), which can be large.

Consider a model fo the form

$$
f(X) = \beta_0 + \sum_{m=1}^M \beta_m h_m (X) 
$$

where each $h_m(X)$ is a function in $C$, or a product of two or more such functions.

Similar to forward stepwise linear regression, we try to build a final model using these functions of the inputs (instead of the original inputs)

For a given choice of $h_m$, we estimate the $\beta_m$ using linear squares (i.e., minimizing the residual sum of squares). Hence, the choice of $h_m(X)$ is very important

First, we choose the constant function $h_0(X) =1$ and all of the functions in $C$ are candidates.

At each stage, we consider a new basis function pair all products of a function $h_m$ in the existing model set $M$ with one of the reflected pairs in $C$, i.e., the

$$
\hat{\beta}_{M + 1} h_l(X) \times (X_j -t)_+ + \hat{\beta}_{M + 2} h_l(X) \times (t - X_j )_+, h_l \in M
$$

that produces the largest decrease in training error

$h_l$ here is some basis function that is already in the model

Then, these are added to the model set $M$

<br>

Example:

First, consider adding to the model a function fo the form $\beta_1 (X_j - t)_+ + \beta_2(t-X)j)_+: t \in \{ x_{ij} \}$ (multiplication by the constant function produces the function itself)

Assume that for a particular data set the best choice is $\hat{\beta}_1 (X_2 - x_{72})_+ + \hat{\beta}_2 (x_{72} - X_2)$ we then add this to the set $M$

Then, we consider adding a pair of products of the form

$$
h_m (X) \times (X_j - t)_+
$$

$$
h_m(X) \times (t- X_j)_+, t \in \{  x_{ij} \}
$$

where for $h_m$ we have the choices

$$
h_0(X) = 1, h_1(X) = (X_2 - x_{72})_+
$$

or

$$
h_2(X) = (x_{72} - X_2)_+
$$

For example, the third choice produces functions such as $(X_1 - x_{51})_+ \times (x_{72} - X_2)_+$

The procedure continues until a pre-specified number of terms is in the model, which will be a large model that overfits the data.

Hence, we use backward deletion (i.e., the term that leads to the smallest increase in residual squared error is deleted at each stage). Thus, we have an estimated "best" model $\hat{f}_\lambda$ of each size (number of terms) $\lambda$

We could use cross-validation to choose the best model, but it's computationally intensive. Instead, we use generalized cross-validation, which is defined as

$$
GCV(\lambda) = \frac{\sum_{i=1}^n (y_i - \hat{f}_\lambda(x_i))^2}{(1- M(\lambda)/n)^2}
$$

where $M(\lambda)$ is the effective number of parameters in the model. (i.e., accounting for $\lambda$ and the number of parameters used in selecting the optimal position fo the knots).

Typically, we use $M(\lambda) = r + cK$ where

-   $r$ = number of linearly independent basis functions

-   $K$ = number of knots selected in the forward process

-   $c = 3$ (typically) or 2 if the model is restricted to be additive

**Advantages**

-   A major advantage of these piecewise linear basis functions is that they are "local" (i.e., non-zero in only a small portion of the features space, even when multiplied together), which facilitates model fitting in high dimensions.

-   A computational advantage because it takes on the order of $n$ operations to try very knot in each step of the process (for each of the $j = 1, \dots, p$ variables)

-   If higher order products are in the model, lower order components must also be included in the model. (in reality, we don't have to, but it's a good modeling practice)

-   MARS can be extended to classification settings (e..g, setting the response variable to 0 and 1) but it's artificial. There are specific MARS-like algorithms designed for classification

**Disadvantages**

-   Each input can occur at most one time in a product. Thus, **higher order powers of an input are not allowed**. If you include it, then it can produce unstable fits, particularly at the boundaries

    -   One can also restrict products to be of a certain order (e..g, only second-degree or third-degree)
