# Local Regression

-   This method improve bias from [Kernel Smoothing] at the boundaries by fitting straight lines instead of constants.

-   Also known as the **locally weighted linear regression**

It seeks to

$$
\min_{\alpha(x_0), \beta(x_0)} \sum_{1}^n K_\lambda (x_0, x_i)[y_i - \alpha (x_0) - \beta(x_0)x_i]^2
$$

and gives the estimate $\hat{f}(x_0) =\hat{\alpha}(x_0)+ \hat{\beta}(x_0)x_0$

To fit this, we let $b(x)^T = (1,x)$ then define the $n \times 2$ matrix $\mathbf{B}$ to have i-th row given by $b(x_i)^T$

Then, let $\mathbf{W}(x_0)$ be the $n \times n$ diagonal matrix with the i-th diagonal given by $K_\lambda(x_0, x_i)$. Then

$$
\hat{f}(x_0)=b(x_0)^T (\mathbf{B}^T \mathbf{W}(x_0)\mathbf{B})^{-1}\mathbf{B}^T \mathbf{W}(x_0)\mathbf{y} = \sum_{i=1}^n l_i(x_0)y_i
$$

Thus, the fitted solution is linear in the $y_i$ with the weights in the linear combination given by $l_i(x_0)$, which are a combination of the kernel weights and least squares equations, which is called **equivalent kernel**

An advantage of this method is that it corrects the boundary bias issues to first order (i.e., the bias is only a function of the second derivatives of $f(x_0)$ and so is small on average).

Thus, there is a small price f
