# Discriminant Analysis

Assumption:

-   Multivariate normality

-   Homoskedasticity: assumption for LDA only, QDA can still be used with unequal covariances

-   No Multicollinearity: because it can decrease your predictive power

-   Independent predictors

LDA with $p$ inputs $x$ for $k = 1, \dots ,K$ classes proceeds by finding the minimum value of the discriminant function for a given $x$

$$
\delta_k(x) = x^T \Sigma^{-1} \mu_k - \frac{1}{2} \mu_k^T \Sigma^{-1} \mu_k + \log \pi_k
$$

for each class, where

-   $\Sigma$ is the pooled covariance matrix for all classes

-   $\mu_k$ is the class-specific mean (centroid)

-   $\pi_k$ is the prior probability of being in class $k$

In practice, we don't know the parameters $\Sigma,\mu_k, \pi_k$ and either estimate them or in the case of $\pi_k$ specify them.

The quadratic discriminant function (QDA) follows similarly, except we accommodate a different covariance matrix for each class, $\Sigma_k$, which gives

$$
\delta_k(x) = -\frac{1}{2} \log|\Sigma_k| - \frac{1}{2} (x - \mu_k)^T \Sigma_k^{-1} (x- \mu_k) + \log \pi_k
$$

Virtues of LDA

-   Simple and typically good classifier

-   It's the estimated Bayes classifier if the observations are really from a multivariate normal distribution with a common covariance matrix (unlikely in practice)

-   the decision boundaries are linear, making the decision rule simple to describe and implement

-   Provides a natural low-dimensional view of the data

-   It often works well because it's simple and has low variance.

Problems with LDA

-   Linear boundaries are often not adequate to separate classes. when the sample size is larger, we can efficiently estimate nonlinear boundaries

-   A single centroid for each class is not sufficient many applications

-   In some problems, there may be too many predictors ($p$ is large relative to $n$) and LDA has too many parameters that are estimated with high variance

<br>

Extensions of LDA

-   Recast the LDA problem as a linear regression problem, and then generalize it to include functions of the $x$ inputs - so called "flexible discriminant analysis" (FDA)

    -   FDA also stands for "Functional Data analysis" in the broader statistical jargon

-   Penalize the coefficients in the LDA when there are too many coefficients

-   Model each class as a mixture of two or more Gaussians with different centroids, but with all fo the Gaussians sharing the same covariance matrix .

<br>

Background

-   Related to fining lower-dimensional linear classifiers (R.A. Fisher), his idea was to obtain a reasonable representation of the class population that involved only a few linear combination fo the observation (e.g., $a_1' x, a_2'x, \dots$ (which can be useful for visual inspection or graphical description of the class centroids). This is also described as "reduced-rank linear discriminant analysis [@hastie2001a, 4.3.3]

-   The idea is we seek a reduced set of **canonical** or **discriminant variables** to represent the classification. To implement this, we need

    -   the between-class covariance matrix $\mathbf{B}$

    -   the within-class covariance matrix $\mathbf{W}$

## Reduced-Rank LDA

We define the between and within-class covariance matrices as:

$$
\mathbf{B} = \sum_{k=1}^K (\mu_k - \mu)(\mu_k - \mu)'
$$

B looks at how far away the centroids are from the overall mean for each group

$$
\mathbf{W} = \sum_{k=1}^K \sum_{j=1}^{n_k} (x_{kj} - \mu_k) (x_{kj}- \mu_k)'
$$

W looks at how far away from the group centroids.

where

-   $\mu_k$ is the $p$-dimensional k-th class mean

-   $\mu$ is the $p$-dimensional overall mean

-   $x_{kj}$ corresponds to the $p$-dimensional input vector fo the j-th element in the k-th group

We then seek the linear combination $Z = a^T X$ such that the **between-class variance is maximized relative to the within-class variance** (i.e., the between-class variance of $Z$ is $a^T \mathbf{B} a$ and the within-class variance is $a^T \mathbf{W}a$)

We seek the $a$ that maximizes the quotient of $a^T \mathbf{B} a$ divided by $a^T \mathbf{W} a$

The solution to the maximization problem is the "a" given by the eigenvector associated with the largest eigven value of $\mathbf{W}^{-1}\mathbf{B}$, which we call $a_1$

One can show that the next direction $a_2$ that maximizes this quotient and is orthogonal to $a_1$ is the eigenvector associated with the next largest eigenvalue, etc.

-   The $a_l$ are referred to as **discriminant coordinates** (not discriminant functions) or canonical **variates**

This sequence of discriminant then provides the low-dimensional presentation fo the data that separates the populations as much as possible.

<br>

In addition to separating the populations, these discriminants can be used to classify.

Let $z_l(x_i) = a^T_l x_i, l = 1, \dots, K-1$ be the discriminants for the $i$-th input $x_i$, which can be shown to have variance of one and are uncorrelated with each other

Then, it can be shown that for an observation, $x$, the squared distance from $z_l(x)$ to the $k$-th class centroid ($\mu_k$) is given by $\sum_{l=1}^{K-1}(z_l (x) - \mu_{z_l^k})^2$, where $\mu_{z_l^k}$ is the mean of $\{z_l(x_j)\}$ for observations $x_j$ in the $k$-th class.

A reasonable classification rule classifies $x$ to class $k$ with the smallest value of this squared distance.

<br>

## Flexible Discriminant Analysis

FDA could be confused with functional data analysis

If we have $L = K - 1$ score functions $\theta_l(i)$ (a function in $R^1$ that assigns scores to the classes so taht they can be modeled by "regression" functions) then we seek these scores and the coefficients $\beta_l$ that minimize the average squared residual

$$
\frac{1}{n} \sum_{l=1}^L [\sum_{i=1}^n (\theta_l (i) - x_i^T \beta_l)^2]
$$

Importantly, **the sequence of** $\beta_l$**'s can be shown to be the same as the discriminant (canonical) vectors** ($a_l$) in the [Reduced-Rank LDA] methodology, up to a constant, and the scores ($\theta_s$) correspond to the $Z$'s

The $\beta$ coefficients act like linear regression coefficients, which mean we can generalize this procedure as we did in nonparametric regression and replace the regression fits by some more flexible class of functions, $\eta_l(x)$ (e.g., [Spline][Spline Regression], [MARS][Multivariate Adaptive Regression Splines], etc.)

Hence, a more general classifier is defined by

$$
\frac{1}{n} \sum_{l=1}^{L} [\sum_{i=1}^n (\theta_l(i) - \eta_l(x_i))^2 + \lambda J(\eta_l)]
$$

where we include the regularization term fro some forms of nonparametric regression (e.g., [Smoothing splines][Spline Regression], etc.)

Additive spline is a more flexible approach (called "bruto" can be found in `mda` package in R). More details can be found [@hastie2001a 12.5.1]

<br>

## Penalized Discriminant Analysis

[Flexible Discriminant Analysis] is a form of regularized discriminant analysis.\
For example, consider an FDA with a linear regression onto a basis expansion $h(x)$, with a quadratic penalty on the coefficients,

$$
\frac{1}{n} \sum_{l = 1}^L [\sum_{i=1}^n ( \theta_l(i)- h^T (x_i)\beta_l)^2 + \lambda \beta_l^T \mathbf{\Omega} \beta_l]
$$

where the choice of $\mathbf{\Omega}$ depends on the specific problem,

For example, if $\eta_l(x) = h(x)^T \beta_l$ is an expansion on the spline basis functions, $\Omega$ might constrain $\eta_l$ to be smooth

The idea is that we seek to **give more weight to "smooth" coefficients and less weight to "rough" ones, which can be seen if we consider highly correlated predictors** (such as with images).

This procedure is known as [Penalized Discriminant Analysis]

<br>

## Mixture Discriminant Analysis

We sometimes refer to LDA as a prototype analysis in that there is just a single centroid for each class.

More generally, such a single prototype classifier might be sufficient if the classes are inhomogeneous.

In that case, we might consider a mixture of Gaussian models to present each class.

Recall, a Gaussian mixture model for the k-th class has density

$$
P(X|G= k ) = \sum_{r=1}^{R_k} q_{kr} \phi(X; \mu_{kr}, \Sigma)
$$

where the mixing proportions $q_{kr}$ sum to 1.

In this case, there are $R_k$ mixtures (prototypes) for the k-th class

But, notice that we are assuming the **same covariance matrix** $\Sigma$ for each class and each prototype (estimating different covariance matrices can be expensive).

Estimating the parameters corresponding to this distribution can be tricky as the optimization can be difficult.

Typically, we use the expectation-maximization (E-M) algorithm [@hastie2001a 12.7] or a fully-Bayesian implementation.

## Large p, small n Approaches

Consider some procedures that are especially suited for the large p, small n case

-   [Diagonal Linear Discriminant Analysis]

-   [Nearest Shrunken Centroids]

### Diagonal Linear Discriminant Analysis

When $p >> n$, it's not possible to fit a full LDA without some sort fo regularization.

A simple type of regularization assumes **independence of the features within class**

Thus, the within-class covariance matrix is just a diagonal matrix

But in reality, this typically isn't true, but we don't have enough data to estimate the covariances anyway

the benefit is that this greatly reduces the number of parameters that must be estimated.

Thus, the diagonal-covariance LDA rule is given by the discriminant score (we classify into the class with the maximum of this score):

$$
\delta_k(x^*) = - \sum_{j=1}^p \frac{(x_j^* - \bar{x}_{kj})^2}{s_j^2} + 2 \log \pi_k
$$

where

-   $x^*$ is the p-dimensional test observation

<!-- -->

-   $s_j$ is the pooled within-class standard deviation of the j-th feature

-   $\bar{x}_{kj}$ is the mean of the $n_k$ values for the j-th feature in class $k$

-   $\pi_k$ is the prior probability for class $k$

We say $\bar{x}= (\bar{x}_{k1}, \dots, \bar{x}_{kp})^T$ is the centroid of class $K$

The first part of the diagonal LDA discriminant score is just the (negative) standardized squared distance of $x^*$ to the k-th centroid, and

The second term corresponds to the prior classification probability for class $k$

Thus, we classify $x^*$ into the $k$-th class that has the highest discriminant score. This classifier is often pretty good in high-dimensional settings.\
This procedure is equivalent to the nearest centroid classifier

Unfortunately, this classifier has a drawback in that it uses all $p$ of the features, and thus, it prohibits interpretation.

It's possible with additional regularization, to gain interpretability and improve test error, which gives us the [Nearest Shrunken Centroids]

<br>

### Nearest Shrunken Centroids

To regularize, we remove features that are not contributing to successful classification.

Hence, we shrink the class means toward the overall mean, for each feature separately.

This gives a regularized version of the [Diagonal Linear Discriminant Analysis] or, equivalently, a regularized version of the nearest centroid classifier

The procedure is known as the [Nearest Shrunken Centroids] approach

First, let

$$
d_{kj} = \frac{\bar{x}_{kj} - \bar{x}_j}{m_k (s_j + s_0)}
$$

where $\bar{x}_j$ is the overall mean for the $j$-th feature

$m^2_k = \frac{1}{n_k} - \frac{1}{n}$ and $s_0$ is a small positive constant (usually the median of the $s_j$ values)

We then shrink the $d_{kj}$ toward 0 using the soft thresholding formula

$$
d_{kj}' = sign (d_{kj}) (|d_{kj}| - \Delta)_+
$$

where $\Delta$ is usually determined by cross-validation

Note:

-   $d_{kj}'=0$ if the argument in $(.)_+$ is less than 0

Then, replacing $d_{kj}$ with $d_{kj}'$ and rearranging gives

$$
\bar{x}_{kj}' = \bar{x}_j + m_k (s_j + s_0) d_{kj}'
$$

which are the **shrunken centroids**.

These are then used in place of $\bar{x}_{kj}$ in the discriminant score function for the [Diagonal Linear Discriminant Analysis]

Now, only those **features that have a nonzero** $d_{kj}'$ **for at least one of the classes contribute to the classification rule**, and thus many features are discarded

Example from [@hastie2001a 18.4]

<br>

### Regularized Discriminant Analysis

[@hastie2001a 4.3.1] describes a hybrid approach between quadratic discriminant analysis and LDA where one shrinks the class-specific covariance matrices to a common pooled covariance matrix, which is known as **regularized discriminant analysis**

$$
\hat{\mathbf{\Sigma}}_k (\alpha) = \alpha \mathbf{\hat{\Sigma}}_k + (1- \alpha) \hat{\mathbf{\Sigma}}
$$

In the large p, small n situation, a simple variant of this is sometimes used to address the fact that the sample covariance matrix, $\mathbf{\hat{\Sigma}}_k$ (or $\mathbf{\hat{\Sigma}}$) is singular when $n < p$

In particular, we can consider

$$
\hat{\mathbf{\Sigma}}_k (\gamma) = \gamma \hat{\mathbf{\Sigma}} + (1 - \gamma) diag (\hat{\mathbf{\Sigma}})
$$

for $\gamma \in [0,1]$ (i.e., when $\gamma \neq 1$ there is shrinkage of the sample covariance matrix toward its diagonal)

This has a similar flavor to ridge regression \@ref(ridge-regression), but shrinks to a diagonal matrix.

Typically, $\gamma$ is chosen by cross-validation

Sometimes this is known as $L_2$**-penalized discriminant analysis**

<br>

### Logistic Regression with Quadratic Regularization

We can also regularize multi-class logistic regression.\
Consider a multi-class extension to logistic regression known as the **symmetric multiclass logical model** (multinomial):

$$
Pr(G = k |X=x) = \frac{\exp(\beta_{k0} + x^T \beta_k)}{\sum_{l=1}^K \exp(\beta_{l0} + x^T \beta_l)}
$$

To deal with the $p >>n$ problem, we can regularize by maximizing the $L_2$-penalized log-likelihood

$$
\underset{\{\beta_{k0}, \beta_k\}_1^K}{\operatorname{max}} [ \sum_{i=1}^n \log Pr(g_i|x_i) - \frac{\lambda}{2}\sum_{k=1}^K ||\beta_k ||^2]
$$

This automatically forces $\sum_{k=1}^K \hat{\beta}_{kj} = 0$ for $j = 1,\dots, p$

A nice feature of the $L_2$ penalty is that it tends to shrink **correlated parameters toward each other.**

However, it doesn't shrink the parameters to exactly zero.

### Other Regularization Penalties

We could consider an $L_1$ (lasso \@ref(lasso-regression)) penalty for the logistic classification, which would have the advantage in that a subset of the $\beta$ parameters will be shrunk to exactly 0.

Thus, we want to maximize the following penalized log-likelihood:

$$
\underset{\{\beta_{k0}, \beta_k\}_1^K}{\operatorname{max}} [\sum_{i=1}^n \log Pr (g_i |x_i) - \lambda \sum_{k=1}^K \sum_{j=1}^p | \beta_{kj}|]
$$

Another useful penalty is the **elastic net penalty**, which is a mixture of the $L_1$ and $L_2$ penalties and takes the form:

$$
\sum_{j=1}^p (\alpha|\beta_j| + (1- \alpha) \beta_j^2)
$$

This is a useful penalty because

-   the $L_2$ portion encourages common shrinkage for correlated parameter and

-   the $L_1$ portion encourages sparsity (e.g., many coefficients shrunk to exactly 0)

<br>

One can also build penalty function that performs regularization in the context when "nearby" parameters are likely o be dependent e.g., as in spatial, time series, and functional data analysis)

The **fused lasso** is one such example.\
The penalty function for equally spaced parameters is then

$$
\lambda_1 \sum_{j=1}^p |\beta_j| + \lambda_2 \sum_{j=1}^{p-1}|\beta_{j+1}- \beta_j|
$$

the second component can be modified as described in [@hastie2001a 18.4.2] if the parameters are not equally spaced but are still "neighbors."

This can be extended to two-dimensional distances in the case of image data. [@hastie2001a 18.4.2] show an example for a model of genome order of a gene in a tumor sample using what they call the fused lasso signal approximator which solves

$$
\underset{\beta \in R^n}{\operatorname{min}} \{ \sum_{i=1}^n (y_i - \beta_0 - \beta_i)^2 + \lambda_1 \sum_{i=1}^n |\beta_i| + \lambda_2 \sum_{i=1}^{n-1} |\beta_{i+1} - \beta_i| \}
$$

The interesting thing about this model is that basically each dat point has its own mean, so there are $n+1$ parameters and $n$ samples. [@hastie2001a 18.8] (basically, we force all points to have the same mean unless the data suggest otherwise)

<br>

As it turns out, the support vector classifier \@ref(support-vector-classifiers) works well in the large p, small n problem.

Although we can add regularization to the SVM, typically when $p >> n$ the unregularized support vector classifier works about well or better than the regularized version

Overfitting is not as much of a problem with the SVM because the inherent dependence on a relatively few support vectors

Remember in the multiclass problem, we can consider the "one versus one" or "one versus all" approaches.
