# Cluster Analysis

Cluster analysis consists of a relatively large set of techniques that are used for finding subgroups, cluster, or segments in a set of features

The idea is that we decide on some way to measure similarity or dissimilarity and try to form clusters that are homogeneous so that observations **in a subgroup are more similar to each other than to other observations not in the subgroup**.

There are a large number of clustering algorithm.\
two of the best-known approaches are **K-means clustering** and **hierarchical clustering**

-   In the case of K-means clustering, we attempt to partition observations into a pre-determined number of clusters

-   In hierarchical, clustering, we either

    -   start with each observation as its own cluster and aggregate them, or

    -   start with one cluster and successively disaggregate them,

    -   in both cases giving a tree or dendrogram representation of the clustering

-   **We can choose to perform clustering on the basis of the features to get subgroups or observations, or in terms of the observations to get subgroups of features**

-   Critical all clustering approaches is the choice of **distance or proximity** or **dissimilarity measure between two objects**.

Both [Discriminant Analysis] and [Cluster Analysis] are used to classify.

|                               | Cluster Analysis      | Discriminant Analysis |
|-------------------------------|-----------------------|-----------------------|
| Under framework               | Unsupervised Learning | Supervised Learning   |
| Dependent variable (category) | No                    | Yes                   |
| Classification rule based on  | Closeness             | Difference            |

<br>

## Proximity Matrices

It's convenient to represent the data in terms of **proximity** (alikeness of affinity)

This can be thought of in terms of similarityor dissimilarity

A similarity measure increases as two objects are more alike, while a dissimilarity measure decreases as two objects become more alike (e.g., Euclidean distance).

Formally, given two $p$-dimensional objects $x_i$ and $x_i'$, a dissimilarity **measure** $d_{ii'}$ satisfies:

1.  $d_{ii'} \ge 0 \forall x_i, x_i'$
2.  $d_{ii'} = 0$ iff $x_i = x_i'$
3.  $d_{ii'} = d_{i'i}$

A measure that satisfies all of these conditions is said to be a **semi**-**metric**

If it further satisfies the triangle inequality, $d_{ii'} < d_{ik} + d_{i'k}$, the it is said to form a **metric**.

We typically form the $n \times n$ **proximity matrix**, $\mathbf{D}$, which in the case of a dissimilarity measure, has $(i,j)$th element given by $d_{ij}$

<br>

### Dissimilarities based on Attributes

In general, we can define the dissimilarity by summing across the $p$ attributes (i.e., equal weighting):

$$
d_{ii'} = D(x_i, x_i') = \sum_{j=1}^p d_j (x_{ij}, x_{i'j})
$$

A very common choice for the dissimilarity metric is squared distance

$$
d_j(x_{ij}, x_{i'j}) = (x_{ij} - x_{i'j})^2
$$

Issues:

1.  We may wish more general distance measures
2.  We may have categorical variables
3.  We may wish to weight the attributes differently

Fixes

1.  A general class of dissimilarities is the **Minkowski metric**

$$
d_{ii'} = (\sum_{j=1}^p | x_{ij} - x_{i'j}|^\lambda)^{1/\lambda}
$$

Consider the situation when we have ordinal variables (e..g, categorical variables that have order)

Typically, one converts these to a numerical value then uses a quantitative metric.

For example, say we have $M$ ordinal values, we can then replace these with $(i - 1/2)/M$ for $i = 1, \dots, M$

For unordered categorical (nominal) variables, the degree-of-difference between pairs of values must be specified directly. These are selected in a way to maintain the symmetric nature of the dissimilarity matrix

And it's common to weight the elements of the discrepancy function differently depending on attribute

$$
D(x_i, x_i') = \sum_{j=1}^p w_j d_j (x_{ij}, x_{i'j}); \sum_{j=1}^p w_j = 1
$$

where $w_j$ is a weight assigned to the j-th attribute

As discussed in [@hastie2001a 14.3.3], setting the $w_j$ to the same value for each variable does not necessarily give all of the attributes equal weight.

They show that setting $w_j$ proportional to $1/\bar{d}_j$ where

$$
\bar{d}_j = \frac{1}{n^2} \sum_{i=1}^n \sum_{i' = 1}^n d_j (x_{ij}, x_{i'j})
$$

gives all attributes equal influence, which is not always a good thing in terms of finding subgroups

## Combinatorial Cluster Algorithms

Let each observation be uniquely labeled by an integer $i \in \{1, \dots, n\}$. A pre-specified number of clusters $K<n$ is then assumed, and each cluster is labeled by an integer $k \in \{ 1, \dots, K \}$

Each observation is assigned to one unique cluster.

The assignment is characterized by an **encoder**, $k = C(i)$ which assigns the $i$-th observation to the $k$-th cluster

We seek an encoder based on the dissimilarities $d(x_i, x_i')$ between every pair of observations.

We have to specify some "**loss**" **function** that we would like to minimize for clustering. One approach is to define

$$
W(C) = \frac{1}{2} \sum_{k=1}^K \sum_{C(i)= k} \sum_{C(i') = k} d(x_i, x_{i'})
$$

$$
B(C) = \frac{1}{2} \sum_{k=1}^K \sum_{C(i) = k} \sum_{C(i') \neq k} d(x_i, x_{i'})
$$

$$
T = \frac{1}{2} \sum_{i=1}^n \sum_{i'=1}^n d(x_i, x_{i'}) = W(C) + B(C)
$$

K-Means Clustering

1.  randomly assign a number ($1 \to K$), to each of the observations, which will be initial cluster assignments.

2.  Iterate until the cluster assignments stop changing:

    1.  For each of the K clusters, compute the cluster **centroid**. The k-th cluster centroid is the vector of the p feature means for the observations in the k-th cluster

    2.  Assign each observation to the cluster whose centroid is close (where closest is defined by Euclidean distance).

Hierarchical Clustering

1.  Begin with n observations and a measure (e.g., Euclidean distance) of all the $\binom{n}{2}= n(n-1)/2$ pairwise dissimilarities. Treat each observation as its own cluster.

2.  For $i = n, n-1, \dots, 2$:

    1.  Examine all pairwise inter-cluster dissimilarities among the $i$ clusters and identify th pair of clusters that are least dissimilar (i.e., most similar). Fuse these two clusters. The dissimilarity between these two clusters indicates the height in the dendrogram at which the fusion should be placed

    2.  Compute the new pairwise inter-cluster dissimilarities among he $i-1$ remaining clusters.
