# Deep Learning

[@LeCun_2015] for a review. [@LeCun_2015] defines a deep-learning architecture as "a multilayer stack of simple modules, all (or most) of which are subject to learning, and many of which compute non-linear input-output mappings".  


## Neural Network  

Neuron  

$$
z = a_1 w_1 + .. + a_k w_k + b
$$


Sigmoid function  

$$
\sigma (z) = \frac{1}{1 +e^{-z}}
$$

Different connections lead to different network structures  

The neurons have different values of weights and biases.  
Fully connected Feedforward Network  



Framework  

 Step 1: A set of function  
 Step 2: Goodness of function f  
 Step 3: Pick the best function  

### Step 1: A set of function

Deep = many hidden layers  


Universality Theorem  
Any continuous, function f  

$$
f: R^N \to R^M
$$
can be realized by a network with one hidden layer (given enough hidden neurons).  

Output layer  

 * Softmax layer as the output layer  
    + probability: 
        - $1 > y_i > 0$  
        - $\sum_i y_i = 1$
    + Monotonicity  
    + Non-locality  

### Step 2: Goodness of function  

Loss can be square error or cross entropy between the network output and target.  

With softmax, the summation of all the outputs would be one. 

A good function should make the loos of all examples as small as possible  


Total Loss: 

$$
L = \sum_{r=1}^R l_r
$$

Find a function in function set (the network parameters $\theta^*$) that minimizes total loss. 

### Step 3: Pick the best function  

Find network parameters $\theta^*$ that minimize total loss L.  

**Gradient Descent**  

Network parameters $\theta = (w_1,w_2,..,b_1,b_2,...)$  

 * Pick an initial value for w  
 * Compute $\frac{\partial L}{\partial w}$,  
    + if negative, increase w  
    + if positive, decrease w  
 * $w_{new} = w_{old} - \eta \frac{partial L}{\partial w}$ where $\eta$ is the learning rate.  
 * You have problems with:  
    + plateau: $\frac{\partial L}{\partial w} \approx 0$  
    + saddle point: $\frac{\partial L}{\partial w} = 0$  
    + Stuck at local minima: $\frac{\partial L}{\partial w} = 0$  
 * solution:  
    + Different initial point to reach different minima, so different results.  
    
Backpropagation  

 * is an efficient way to compute $\partial L / \partial w$



### Recipe of Deep learning

1. Not good result on training data

 * [Choosing proper loss]
 * [Mini-batch]
 * [New activation function]
 * [Adaptive Learning Rate]
 * [Momentum]

2. Not good result on testing data 

 * [Early Stopping]
 * [Regularization]
 * [Dropout]
 * [Network Structure]


#### Choosing proper loss

When using softmax output layer, choose cross entropy. [Problem](http://proceedings.mlr.press/v9/glorot10a/glorot10a.pdf)

#### Mini-batch

```{python eval = FALSE}
model.fit(x_train,y_train,batch_size = 100,nb_epoch = 20) # 100 examples in a mini-batch 
# repeat 20 times
```

 * Randomly initialize network parameters 
 * One epoch
    + Pick the 1st batch $L'= l^1 + l^{31} + ..$ Update parameters once.  
    + Pick the 2nd batch $L''=l^2 + l^{16} +...$ Update parameters once  
    + Until all mini-batches have been picked
 * Repeat the above process
 * Mini-batch is faster (with mini-batch. if there are 20 batches, update 20 times in one epoch).
 

#### New activation function

 * Rectified Linear Unit (ReLU)  

Reason:  

 1. Fast to compute
 2. Biological reason  
 3. Infinite sigmoid with different biases  
 4. Vanishing gradient problem.


Parametric ReLU (PReLU) [@Glorot_2011]

ReLU - Variant  

 * Leaky ReLU  
 * Parametric ReLu  


#### Adaptive Learning Rate

 * Set the learning rate $\eta$ carefully  
 * If learning rate is too large  
 * Total loss may not decrease after each update.  
 * If learning rate is too small
 * Training would be too slow  
 * Popular and simple idea: reduce the learning rate by some factor every few epochs.  
    + At the beginning, we are far from the destination, so we use larger learning rate  
    + After several epochs, we are close to the destination, so we reduce the learning rate  
    + E.g., 1/t decay $\eta^t = \eta \sqrt{t+1}$
 * Learning rate cannot be one-size-fits-all  
    + Giving different parameters different learning rates.  
 * $\eta$ is unit-dependent  (from 0 to 1)


<br>

Adagrad  

 * Original: $w \leftarrow w - \eta \partial L /\partial w$  
 * Adagrad: $w \leftarrow - \eta_{w} \partial L / \partial w$  
    + where $\eta_w$ is parameter dependent learning rate.  
$$
\eta_w = \frac{\eta}{\sqrt{\sum_{i=1}^{t}(g^i)^2}}
$$
    + $\eta$ is constant 
    + $g^i$ is $\partial L / \partial w$ obtained at the i-th update. 
 * Learning rate is smaller and smaller for all parameters  
 * Smaller derivatives, larger learning rate, and vice versa.


[link](https://courses.cs.washington.edu/courses/cse547/15sp/slides/adagrad.pdf)

#### Momentum

Hard to find optimal network parameters 

Movement = negative of $\partial L/ \partial w$ + Momentum  

```{python eval = FALSE}
# RMSProp (Advanced Adagrad) + Momentum
model.compile(loss='categorial_crossentropy',optimizer = SGD(lr=0.1),metrics = ['accuracy'])
model.compile(loss='categorial_crossentropy',optimizer=Adam(),metrics = ['accuracy'])
```


#### Early Stopping

 * training data and testing data can be different.  
 * Learning target is defined by the training data  
 * The parameters achieving the learning target do not necessary have good results on the testing data.  

#### Regularization

#### Dropout

Training

 * each time before updating the parameters  
    + each neuron has p% to dropout.  
        - The structure of the network is changed.  
    + Using the new network for training  
        - For each min-batch, we resample the dropout neurons.  

Testing

 * No dropout  
    + If the dropout rate training is p%, all the weights times 1-p%  
    + Assume that the dropout rate is 50%. If a weight w = 1 by training, set w = 0.5 for testing.  


Dropout is a kind of ensemble.

 * training of dropout: M neurons $\to$ $2^M$ possible networks.  
 * Using one mini-batch to train one network  
 * Some parameters int eh network are shared.  


 * Training of dropout: assume dropout rate is 50%  
 * Testing of dropout: weight

```{python eval = FALSE}
model = Sequential()
model.add(Dense(input_dim = 28*28,output_dim = 500))
model.add(Activation('sigmoid'))
model.add(dropout(0.8))
model.add(Dense (output_dim=500))
model.add(Activation('sigmoid'))
model.add(dropout(0.8))
model.add(Dense(output_dim = 10))
model.add(Activation('softmax'))
```

#### Network Structure

Convolutional Neural Network (CNN)  

 * Widely used in image processing
 * use in [the first step][Step 1: A set of function] for deep learning  


The Whole CNN  

 * Property 1: Some patterns are much smaller than the whole image  
 * Property 2: The same patterns appear in different regions.  
 * Property 3: Subsampling the pixels will not change the object.  

CNN in Keras: only modified the network structure and input format (vector to 3-D tensor)  


```{python eval = FALSE}
model2.add(Convolution2D(25,3,3),input_shape= (1,28,28)) 
# 25 3x3 filters; 1:black/weight, 3: RFB, 28x28 pixels
model2.add(MaxPooling2D(2,2))
model2.add(Convolution2D(50,3,3))
model2.add(MaxPooling2D(2,2))
model2.add(Flatten())
model2.add(Dense(output_dim = 100))
model2.add(Activation('relu'))
model2.add(Dense(output_dim=10))
model2.add(Activation('softmax'))
```










will we always have to know our classes?
Yes, and you have to retrain your model all the time. Or you could use  
Transfer learning in deep learning  




Neural topic modeling  


graph representation learning  

GNN  

DGL  

recurrent network  














BERT model 

## Overview

 
 * What is deep learning?
Input to output via layers of representation

 * What are layers?
A layer is a geometric transformation function on the data that goes through it Weights determine the data transformation behavior of a layer  

<br>
Learning Representation  

 * Transforming input data into useful representation  
 
<br>

The "deep" in deep learning  

 * multiple layers 
 * Other possibly more appropriate names for the field:
    + Layered representations learning 
    + Hierarchical representations learning 
    + Chained geometric transformation learning  
    
<br>
New problem domains for R:  

 * Computer vision  
 * Computer speech recognition  
 * Reinforcement learning applications  
 
<br>
How do we train deep learning models?  

 * Basic of machine learning algorithms  
 * Machine learning vs. statistical modeling  
 * MNIST example  
    + Model definition in R  
    + Layers of representation  
 * The training loop  
 
<br>
Machine learning algorithms  
Learning model parameters via exposure to many example data points  

<br>
Statistics: Often focused on inferring the process by which data is generated 
Machine Learning: Principally focused on predicting future data  

<br>
Deep learning frontiers  

 * Computer vision 
 * Natural language processing 
 * Time series 
 * Biomedical  


\pagebreak


## Tensor Flow and R
TensorFlow APIs  

 * Keras API  
 * Estimator API  
 * Core API  

<br>

### R packages 
TensorFlow APIs 
 * keras: Interface for neural networks, with a focus on enabling fast experimentation. 
 * tfestimators: Implementations of common model types such as regressors and classifiers.  
 * tensorflow: Low *level interface to the TensorFlow computational graph. 
 * tfdatasets: Scalable input pipelines for TensorFlow models.

Supporting Tools 
 * tfruns : Track , visualize, and manage TensorFlow training runs and experiments 
 * tfdeploy : Tools designed to make exporting and serving TensorFlow models straightforward. 
 * cloudml : R interface to Google Cloud Machine Learning Engine.  

R interface to Keras  

 * Step by step example  
 * [Keras layers]  
 * [Compiling models]  
 * [Losses, Optimizers, and Metrics] 
 * More examples  

<br>

### Keras layers  
65 layers available  

 * Dense layers: classic "fully connected" neural network layers  
 * Convolutional layers: "Filters for learning local patterns in data  
 * Recurrent layers: Layers that maintain state based on on previously seen   data 
 * Embedding layers: Vectorization of text that reflects semantic relationships between words  


## Compiling models
Model compilation prepares the model for training by:  
1. Converting the layers into a TensorFlow graph  
2. Applying the specified loss function and optimizer  
3. Arranging for the collection of metrics during training  

## Losses, Optimizers, and Metrics
All available at Keras for R [cheatsheet](https://github.com/rstudio/cheatsheets/raw/master/keras.pdf)


Example of [Image classificaiton](https://blogs.rstudio.com/ai/posts/2017 *12 *14 *image *classification *on *small *datasets/)

## NYU
Materials in this chapter is based on [NYU Deep Learning](https://atcold.github.io/pytorch-Deep-Learning/)

Deep in Deep Learning means multi-layers. "A deep network has several layers and uses them to build a hierarchy of features of increasing complexity"

Supervised Learning (= Function Optimization): With inputs and outputs, you train the machine to tweak its parameter to have the correct outputs from inputs. 
In "traditional machine learning", you have to engineer **feature extractor**, but in deep learning you can multi-layers feature extractor can be trained. And all layers are non-linear, because if they are linear, then all layers would be collapse into one layer. 

Natural Data is compositional. Hence, it is efficiently representable hierarchically. 

Revolutions in Deep Learning:  

 * Speech Recognition: 2010
 * Image Recognition: 2013
 * Natural Language Processing (NLP): 2015


Deep Learning = Learning Representations/ Features
Representation means you turn raw data into something useful   


Image Recognition:  
Pixel, edge, texton, motif, part, object 

Text  
Character, group, word group, clause, sentence, story  

Speech  
Sample, spectral band, sound, phone, phoneme, word. 

Difference between Deep Learning Support-Vector Machines (SVM)  

SVM is a 2-layer neural net, where  

 * layer 1 = templates
 * layer 2 = linear classifier. 

where Deep Learning is "A deep network has several layers and uses them to build a hierarchy of features of increasing complexity"

Deep Machines are more efficient than SVM in representing certain classes of functions. 

The Manifold Hypothesis "states that real-world high-dimensional data lie on low-dimensional manifolds embedded within the high-dimensional space"  

Difference between Deep Learning and PCA (Principal Components Analysis) is that Deep learning uses non-linear function, while PCA uses linear function. 
